version: "3.9"

services:
  app:
    build:
      context: .
      args:
        DEV: "true"  # Match the ARG name in Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - PYTHONUNBUFFERED=1
    command: >
        sh -c "python app/manage.py runserver 0.0.0.0:8000"